# This is a basic workflow to help you get started with Actions

name: Pricing Engine BB Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches:
      - master
      - develop
      - 'release/**'
  pull_request:
    branches:
      - master
      - develop
      - 'release/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOCKER_COMPOSE_VERSION: 1.25.4

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Setup Python 3.6.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9
      # Runs a set of commands using the runners shell
      - name: Testing
        run: |
          sudo apt-get install jq python3-venv
          pip install -r ./src/requirements.txt
          pytest ./tests
      - name: Container Creation and Publishing
        run: ./travis/containerCreation.sh um-pricing-engine
      - name: Smoke and Acceptance Test
        run: ./travis/acceptanceTest.sh um-pricing-engine 8080 7000
      - name: Release Container
        if: branch = master AND NOT type IN (pull_request)
        run: ./travis/release.sh um-pricing-engine
        
      
        
        
